service: bookkeeper-backend

frameworkVersion: '3'

plugins:
  - serverless-scriptable-plugin
  - serverless-dynamodb
  - serverless-offline

custom:
  serverless-dynamodb:
    stages:
      - development
    start:
      docker: true
      port: 8000
      inMemory: true # change to false if persistent data would be more convenient
      migrate: true
      seed: true
      convertEmptyValues: true
    seed:
      domain:
        sources:
          - table: bookkeeperUsers
            rawsources: [./serverless/data/users/data.dev.json]
          - table: bookkeeperReports
            rawsources: [./serverless/data/reports/data.dev.json]
  scriptable:
    hooks:
      after:aws:deploy:finalize:cleanup: node ./dist/serverless/seed.js ap-southeast-2

provider:
  environment:
    NODE_ENV: ${opt:stage, 'not_set'}
  name: aws
  runtime: nodejs20.x
  region: ap-southeast-2
  iam:  
    role:
      name: bookkeeper-backend-role
      statements:
        - Effect: Allow
          Action: 'secretsmanager:GetSecretValue'
          Resource: 'arn:aws:secretsmanager:ap-southeast-2:290153383648:secret:Secrets-K5NU5a'
        - Effect: Allow
          Action: dynamodb:*
          Resource:
            - 'arn:aws:dynamodb:ap-southeast-2:290153383648:table/bookkeeperUsers/index/*'
            - 'arn:aws:dynamodb:ap-southeast-2:290153383648:table/bookkeeperUsers'
            - 'arn:aws:dynamodb:ap-southeast-2:290153383648:table/bookkeeperReports/index/*'
            - 'arn:aws:dynamodb:ap-southeast-2:290153383648:table/bookkeeperReports'

resources:
  Resources:
    reportsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: bookkeeperReports
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: reportDate
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        GlobalSecondaryIndexes:
          - IndexName: reportDate
            KeySchema:
              - AttributeName: reportDate
                KeyType: HASH
            Projection:
              ProjectionType: 'ALL'
        BillingMode: PAY_PER_REQUEST
    usersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: bookkeeperUsers
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: username
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        GlobalSecondaryIndexes:
          - IndexName: username
            KeySchema:
              - AttributeName: username
                KeyType: HASH
            Projection:
              ProjectionType: 'ALL'
        BillingMode: PAY_PER_REQUEST


functions:
  api:
    handler: dist/lambda.handler
    events:
      - http:
          method: any
          path: /{proxy+}
          cors: true